P(A/B)=(P(B/A).P(A))/P(B)
Find Posterior probabilities of both cases y=1,y=0
and 
p(Y=1|X) probability of y=1 given x is         (P(x|y=1).p(y=1))/p(x)
P(Y=0|X) probability of y=0 given x
argmax(p(y|x))# find the maximum index
PRIOR probability is count '0 or 1'/total_emails
i.e P(y=0) or P(y=1)

X=get unlimited data at 95% discounted price

p(x/y=1) in how many spam emails,these words are occuring.count the frequency of these words in spam email.

p(x/y=0) in how many non-spam emails,these words are occuring.count the frequency of these words in non-spam email.
assumptions- All features are independent

In [117]:
#play golf dataset
# y=play golf
#final value required P(Y=1|X)=PRODUCT(1-N)(p(xi|y=1).P(Y=1)
# and P(Y=0|X) SIMILAR TO ABOVE
#p(Y=1) IS SIMPLE JUST FIND ALL THE YES AND DIVIDE BY TOTAL
 #P(xi|y=1) just compare all the values of x with the given values of x


In [118]:
import pandas as pd   
import numpy as np  


In [119]:
golf=pd.read_csv("golf.csv")


In [120]:
golf

Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [121]:
def prior_prob(golf,label):
    total_examples=golf.shape[0]
    class_examples=(golf['Play']==label).sum()
    return class_examples/total_examples

In [122]:
PRIOR={
    'yes':prior_prob(golf,'yes'),
    'no':prior_prob(golf,'no')
}

In [123]:
PRIOR

{'yes': 0.6428571428571429, 'no': 0.35714285714285715}

In [124]:
def cond_prob(golf,feature,feature_val,label):
    filtered_data=golf[golf['Play'] == label] #extracting rows where we have 'yes','no' whichever we want
    numinator=np.sum( filtered_data[feature]==feature_val)
    denominator=filtered_data.shape[0]

    return numinator/denominator

In [125]:
cond_prob(golf,'Windy',False,'no')

0.4

In [126]:
features=list(golf.columns)[:-1]

In [127]:
COND_PROB={}

for label in golf['Play'].unique():
    COND_PROB[label]={}   #  SAY STORE ALL THE FEATURES FOR YES
    for feature in features:
        COND_PROB[label][feature]={} 
        feature_values=golf[feature].unique()

        for fea_val in feature_values:
            prob=round(cond_prob(golf,feature,fea_val,label),2) 
            COND_PROB[label][feature][fea_val]=prob
            print(feature,fea_val,label,prob)
        print()

Outlook sunny no 0.6
Outlook overcast no 0.0
Outlook rainy no 0.4

Temperature hot no 0.4
Temperature mild no 0.4
Temperature cool no 0.2

Humidity high no 0.8
Humidity normal no 0.2

Windy False no 0.4
Windy True no 0.6

Outlook sunny yes 0.22
Outlook overcast yes 0.44
Outlook rainy yes 0.33

Temperature hot yes 0.22
Temperature mild yes 0.44
Temperature cool yes 0.33

Humidity high yes 0.33
Humidity normal yes 0.67

Windy False yes 0.67
Windy True yes 0.33



In [128]:
COND_PROB

{'no': {'Outlook': {'sunny': 0.6, 'overcast': 0.0, 'rainy': 0.4},
  'Temperature': {'hot': 0.4, 'mild': 0.4, 'cool': 0.2},
  'Humidity': {'high': 0.8, 'normal': 0.2},
  'Windy': {False: 0.4, True: 0.6}},
 'yes': {'Outlook': {'sunny': 0.22, 'overcast': 0.44, 'rainy': 0.33},
  'Temperature': {'hot': 0.22, 'mild': 0.44, 'cool': 0.33},
  'Humidity': {'high': 0.33, 'normal': 0.67},
  'Windy': {False: 0.67, True: 0.33}}}

In [129]:
#PREDICTION
X_test=['sunny','hot','normal',False]

In [130]:
for label in golf['Play'].unique():
    prior=PRIOR[label]
    likelihood=1.0
    for i in range(len(features)):
        feature=features[i]
        fea_val=X_test[i]
        likelihood=COND_PROB[label][feature][fea_val]
    post=likelihood*prior
    print(label,post)

no 0.14285714285714288
yes 0.43071428571428577


USING sklearn


In [131]:
#label encoder is used to covert text data into numeric as sklearn can't work with text data
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
golf['Outlook']=le1.fit_transform(golf['Outlook'])


In [132]:
le2=LabelEncoder()
golf['Temperature']=le2.fit_transform(golf['Temperature'])


In [133]:
le3=LabelEncoder()
golf['Humidity']=le3.fit_transform(golf['Humidity'])

In [134]:
le4=LabelEncoder()
golf['Windy']=le4.fit_transform(golf['Windy'])

In [135]:
le5=LabelEncoder()
golf['Play']=le5.fit_transform(golf['Play'])

In [136]:
from sklearn.naive_bayes import CategoricalNB

In [137]:
model=CategoricalNB()

In [138]:
x=golf.iloc[:,:-1]
y=golf.iloc[:,-1]

In [139]:
model.fit(x,y)

CategoricalNB()

In [140]:
x_test=['sunny','hot','normal',False] # we need to transform these features first


In [141]:
le1.transform(['sunny'])

array([2])

In [142]:
le2.transform(['hot'])

array([1])

In [143]:
le3.transform(['normal'])

array([1])

In [144]:
le4.transform([False])

array([0], dtype=int64)

In [145]:
X_test=np.array([[2,1,1,0]])

In [146]:
model.predict(X_test)

c:\Users\91836\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([1])

In [147]:
# 1 is yes here 
model.predict_proba(X_test)

c:\Users\91836\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.33508723, 0.66491277]])